In [1]:
import numpy as np


In [14]:
arr1=np.array([1,2,3,4,5])
print(np.vander(arr1))

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [2]:
arr=np.array([3,5,7,2,8,10,11,65,72,81,99,100,150])
k=3

In [11]:

def moving_avg(arr,k):
    l=[]
    i=0
    j=k
    while j<=len(arr):
        l.append(sum(arr[i:j])/k)
        i=i+1
        j=j+1
    print(l)

In [12]:
f=moving_avg(arr,k)

[5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
